// Comércios parceiros (mock, gerados proceduralmente pra simular densidade real de
// pequeno comércio — ~400 pontos espalhados pelo Vale do Sinos: Novo Hamburgo, São
// Leopoldo, Sapiranga, Campo Bom, Estância Velha, Ivoti e Portão). Pra um protótipo real,
// isso vira uma tabela alimentada pelos próprios parceiros, com endereço e cadastro de verdade.
export const PARTNERS = [
  { id: "floricultura-buque", name: "Floricultura Buquê", category: "floricultura", lat: -29.7545, lon: -51.1249, blurb: "flores frescas todo dia" },
  { id: "pizzaria-forno-a-lenha", name: "Pizzaria Forno a Lenha", category: "pizzaria", lat: -29.7593, lon: -51.162, blurb: "fatia avulsa também" },
  { id: "loja-estilo-vale", name: "Loja Estilo Vale", category: "loja de roupas", lat: -29.6208, lon: -50.9688, blurb: "roupa boa e barata" },
  { id: "clinica-odontologica-odonto-bem", name: "Clínica Odontológica Odonto Bem", category: "clínica odontológica", lat: -29.6969, lon: -51.1288, blurb: "avaliação rápida" },
  { id: "papelaria-ponto-do-aluno", name: "Papelaria Ponto do Aluno", category: "papelaria", lat: -29.656, lon: -50.9934, blurb: "material escolar e impressão" },
  { id: "banca-noticia-ja", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7788, lon: -51.1704, blurb: "revista e jornal do dia" },
  { id: "lavanderia-vale-limpo", name: "Lavanderia Vale Limpo", category: "lavanderia", lat: -29.6054, lon: -51.1365, blurb: "lavagem rápida self-service" },
  { id: "lanchonete-central", name: "Lanchonete Central", category: "lanchonete", lat: -29.764, lon: -51.1679, blurb: "suco natural também" },
  { id: "bicicletaria-ciclo-bom", name: "Bicicletaria Ciclo Bom", category: "bicicletaria", lat: -29.6753, lon: -51.1139, blurb: "troca de câmara e ajuste de freio, rapidinho" },
  { id: "conveniencia-sempre-aberto", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.6572, lon: -51.1406, blurb: "aberto até tarde" },
  { id: "clinica-odontologica-dente-sadio", name: "Clínica Odontológica Dente Sadio", category: "clínica odontológica", lat: -29.6525, lon: -51.0788, blurb: "avaliação rápida" },
  { id: "mercado-vizinhanca", name: "Mercado Vizinhança", category: "mercado", lat: -29.6644, lon: -51.1451, blurb: "tem de tudo um pouco" },
  { id: "lanchonete-central-12", name: "Lanchonete Central", category: "lanchonete", lat: -29.6203, lon: -51.0022, blurb: "suco natural também" },
  { id: "salao-beleza-pura", name: "Salão Beleza Pura", category: "salão de beleza", lat: -29.6811, lon: -51.0619, blurb: "corte e escova" },
  { id: "conveniencia-sempre-aberto-14", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.7675, lon: -51.1398, blurb: "aberto até tarde" },
  { id: "sorveteria-bola-de-neve", name: "Sorveteria Bola de Neve", category: "sorveteria", lat: -29.6232, lon: -50.9598, blurb: "sorvete artesanal" },
  { id: "cafe-aroma", name: "Café Aroma", category: "café", lat: -29.7745, lon: -51.1532, blurb: "cafezinho bom e barato" },
  { id: "acougue-central", name: "Açougue Central", category: "açougue", lat: -29.6304, lon: -51.1825, blurb: "carne fresca, corte na hora" },
  { id: "bicicletaria-duas-rodas", name: "Bicicletaria Duas Rodas", category: "bicicletaria", lat: -29.6289, lon: -51.1877, blurb: "aluguel de bike também" },
  { id: "banca-noticia-ja-19", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7843, lon: -51.1547, blurb: "revista e jornal do dia" },
  { id: "loja-estilo-vale-20", name: "Loja Estilo Vale", category: "loja de roupas", lat: -29.7763, lon: -51.1412, blurb: "roupa boa e barata" },
  { id: "restaurante-point-do-almoco", name: "Restaurante Point do Almoço", category: "restaurante", lat: -29.674, lon: -51.1208, blurb: "marmita e prato feito" },
  { id: "livraria-do-saber", name: "Livraria do Saber", category: "livraria", lat: -29.6598, lon: -51.1693, blurb: "boa pra matar um tempo esperando o ônibus" },
  { id: "otica-clara", name: "Ótica Clara", category: "ótica", lat: -29.686, lon: -51.0837, blurb: "exame de vista rápido" },
  { id: "papelaria-vale-papel", name: "Papelaria Vale Papel", category: "papelaria", lat: -29.7694, lon: -51.1574, blurb: "material escolar e impressão" },
  { id: "hortifruti-horta-fresca", name: "Hortifruti Horta Fresca", category: "hortifruti", lat: -29.7532, lon: -51.1606, blurb: "fruta e verdura fresquinha" },
  { id: "doceria-doce-vale", name: "Doceria Doce Vale", category: "doceria", lat: -29.7777, lon: -51.1646, blurb: "docinho pra alegrar o dia" },
  { id: "barbearia-do-seu-ze", name: "Barbearia do Seu Zé", category: "barbearia", lat: -29.6596, lon: -50.9598, blurb: "corte rápido, sem hora marcada" },
  { id: "otica-foco", name: "Ótica Foco", category: "ótica", lat: -29.7021, lon: -51.1342, blurb: "conserto de óculos na hora" },
  { id: "cafe-recanto", name: "Café Recanto", category: "café", lat: -29.6479, lon: -50.9907, blurb: "cafezinho bom e barato" },
  { id: "pizzaria-fatia-boa", name: "Pizzaria Fatia Boa", category: "pizzaria", lat: -29.6645, lon: -51.1101, blurb: "fatia avulsa também" },
  { id: "floricultura-jardim-vale", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.6539, lon: -50.9944, blurb: "flores frescas todo dia" },
  { id: "papelaria-escolar", name: "Papelaria Escolar", category: "papelaria", lat: -29.6866, lon: -51.1443, blurb: "material escolar e impressão" },
  { id: "conveniencia-sempre-aberto-33", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.6322, lon: -50.9885, blurb: "aberto até tarde" },
  { id: "lanchonete-esquina", name: "Lanchonete Esquina", category: "lanchonete", lat: -29.6376, lon: -51.1496, blurb: "lanche rápido no caminho" },
  { id: "restaurante-cantina-do-bairro", name: "Restaurante Cantina do Bairro", category: "restaurante", lat: -29.6988, lon: -51.1219, blurb: "bom pra um almoço rápido" },
  { id: "assistencia-conserta-ja", name: "Assistência Conserta Já", category: "loja de celular", lat: -29.6772, lon: -51.1356, blurb: "troca de tela na hora" },
  { id: "mercadinho-bom-preco", name: "Mercadinho Bom Preço", category: "mercado", lat: -29.7676, lon: -51.1701, blurb: "preço justo" },
  { id: "academia-movimento", name: "Academia Movimento", category: "academia", lat: -29.702, lon: -51.1425, blurb: "aula experimental grátis" },
  { id: "salao-espaco-vaidosa", name: "Salão Espaço Vaidosa", category: "salão de beleza", lat: -29.7489, lon: -51.1678, blurb: "corte e escova" },
  { id: "academia-vale-fit", name: "Academia Vale Fit", category: "academia", lat: -29.8152, lon: -51.1431, blurb: "aula experimental grátis" },
  { id: "conveniencia-24h-vale", name: "Conveniência 24h Vale", category: "loja de conveniência", lat: -29.6745, lon: -51.1126, blurb: "aberto até tarde" },
  { id: "lavanderia-rapida", name: "Lavanderia Rápida", category: "lavanderia", lat: -29.6545, lon: -51.1427, blurb: "lavagem rápida self-service" },
  { id: "doceria-guloseima", name: "Doceria Guloseima", category: "doceria", lat: -29.7713, lon: -51.1218, blurb: "docinho pra alegrar o dia" },
  { id: "sorveteria-point-do-sorvete", name: "Sorveteria Point do Sorvete", category: "sorveteria", lat: -29.695, lon: -51.0685, blurb: "sorvete artesanal" },
  { id: "barbearia-corte-certo", name: "Barbearia Corte Certo", category: "barbearia", lat: -29.7049, lon: -51.2421, blurb: "corte rápido, sem hora marcada" },
  { id: "academia-corpo-ativo", name: "Academia Corpo Ativo", category: "academia", lat: -29.7543, lon: -51.1362, blurb: "aula experimental grátis" },
  { id: "conveniencia-rapidinho", name: "Conveniência Rapidinho", category: "loja de conveniência", lat: -29.6675, lon: -51.1457, blurb: "aberto até tarde" },
  { id: "banca-noticia-ja-48", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.6481, lon: -50.9763, blurb: "revista e jornal do dia" },
  { id: "papelaria-central", name: "Papelaria Central", category: "papelaria", lat: -29.6545, lon: -51.1443, blurb: "cópia rápida" },
  { id: "academia-forca-total", name: "Academia Força Total", category: "academia", lat: -29.6951, lon: -51.2202, blurb: "aula experimental grátis" },
  { id: "bicicletaria-roda-livre", name: "Bicicletaria Roda Livre", category: "bicicletaria", lat: -29.6197, lon: -51.1637, blurb: "aluguel de bike também" },
  { id: "livraria-pagina-viva", name: "Livraria Página Viva", category: "livraria", lat: -29.6717, lon: -51.1342, blurb: "tem seção de segunda mão" },
  { id: "livraria-vale-do-livro", name: "Livraria Vale do Livro", category: "livraria", lat: -29.6704, lon: -51.0695, blurb: "tem seção de segunda mão" },
  { id: "floricultura-flor-de-lis", name: "Floricultura Flor de Lis", category: "floricultura", lat: -29.6943, lon: -51.1251, blurb: "flores frescas todo dia" },
  { id: "sorveteria-bola-de-neve-55", name: "Sorveteria Bola de Neve", category: "sorveteria", lat: -29.6747, lon: -51.142, blurb: "sorvete artesanal" },
  { id: "floricultura-buque-56", name: "Floricultura Buquê", category: "floricultura", lat: -29.631, lon: -51.1934, blurb: "flores frescas todo dia" },
  { id: "oficina-mecanica-rapida", name: "Oficina Mecânica Rápida", category: "oficina mecânica", lat: -29.6015, lon: -51.1758, blurb: "revisão rápida, sem enrolação" },
  { id: "pizzaria-point-da-pizza", name: "Pizzaria Point da Pizza", category: "pizzaria", lat: -29.8072, lon: -51.1473, blurb: "fatia avulsa também" },
  { id: "conveniencia-sempre-aberto-59", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.796, lon: -51.1568, blurb: "aberto até tarde" },
  { id: "salao-charme", name: "Salão Charme", category: "salão de beleza", lat: -29.7759, lon: -51.1348, blurb: "corte e escova" },
  { id: "doceria-ponto-doce", name: "Doceria Ponto Doce", category: "doceria", lat: -29.6329, lon: -51.1619, blurb: "docinho pra alegrar o dia" },
  { id: "acougue-boi-gordo", name: "Açougue Boi Gordo", category: "açougue", lat: -29.6833, lon: -51.134, blurb: "carne fresca, corte na hora" },
  { id: "academia-vale-fit-63", name: "Academia Vale Fit", category: "academia", lat: -29.6781, lon: -51.2191, blurb: "aula experimental grátis" },
  { id: "doceria-ponto-doce-64", name: "Doceria Ponto Doce", category: "doceria", lat: -29.702, lon: -51.1411, blurb: "docinho pra alegrar o dia" },
  { id: "posto-central", name: "Posto Central", category: "posto de gasolina", lat: -29.7735, lon: -51.1612, blurb: "banheiro limpo e loja de conveniência" },
  { id: "academia-forca-total-66", name: "Academia Força Total", category: "academia", lat: -29.7706, lon: -51.1384, blurb: "aula experimental grátis" },
  { id: "padaria-pao-nosso", name: "Padaria Pão Nosso", category: "padaria", lat: -29.8108, lon: -51.1601, blurb: "pão quente saindo do forno" },
  { id: "acougue-do-gaucho", name: "Açougue do Gaúcho", category: "açougue", lat: -29.6596, lon: -51.1435, blurb: "carne fresca, corte na hora" },
  { id: "sapataria-conserta-tudo", name: "Sapataria Conserta Tudo", category: "sapataria", lat: -29.7969, lon: -51.1415, blurb: "conserto de calçado na hora" },
  { id: "bicicletaria-duas-rodas-70", name: "Bicicletaria Duas Rodas", category: "bicicletaria", lat: -29.7534, lon: -51.1538, blurb: "aluguel de bike também" },
  { id: "floricultura-buque-71", name: "Floricultura Buquê", category: "floricultura", lat: -29.68, lon: -51.1285, blurb: "flores frescas todo dia" },
  { id: "hortifruti-verde-vale", name: "Hortifruti Verde Vale", category: "hortifruti", lat: -29.6855, lon: -51.1406, blurb: "fruta e verdura fresquinha" },
  { id: "floricultura-jardim-vale-73", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.6728, lon: -51.0524, blurb: "flores frescas todo dia" },
  { id: "oficina-do-marcao", name: "Oficina do Marcão", category: "oficina mecânica", lat: -29.6738, lon: -51.1534, blurb: "revisão rápida, sem enrolação" },
  { id: "oficina-mecanica-rapida-75", name: "Oficina Mecânica Rápida", category: "oficina mecânica", lat: -29.645, lon: -50.9966, blurb: "revisão rápida, sem enrolação" },
  { id: "sapataria-conserta-tudo-76", name: "Sapataria Conserta Tudo", category: "sapataria", lat: -29.6853, lon: -51.07, blurb: "conserto de calçado na hora" },
  { id: "sorveteria-sabor-gelado", name: "Sorveteria Sabor Gelado", category: "sorveteria", lat: -29.7571, lon: -51.1573, blurb: "sorvete artesanal" },
  { id: "salao-espaco-vaidosa-78", name: "Salão Espaço Vaidosa", category: "salão de beleza", lat: -29.8091, lon: -51.1474, blurb: "encaixe rápido às vezes rola" },
  { id: "doceria-guloseima-79", name: "Doceria Guloseima", category: "doceria", lat: -29.7887, lon: -51.1681, blurb: "docinho pra alegrar o dia" },
  { id: "conveniencia-24h-vale-80", name: "Conveniência 24h Vale", category: "loja de conveniência", lat: -29.6471, lon: -50.971, blurb: "aberto até tarde" },
  { id: "bicicletaria-pedal-vale", name: "Bicicletaria Pedal Vale", category: "bicicletaria", lat: -29.6237, lon: -50.988, blurb: "troca de câmara e ajuste de freio, rapidinho" },
  { id: "otica-foco-82", name: "Ótica Foco", category: "ótica", lat: -29.7587, lon: -51.1357, blurb: "exame de vista rápido" },
  { id: "clinica-odontologica-sorriso-facil", name: "Clínica Odontológica Sorriso Fácil", category: "clínica odontológica", lat: -29.7791, lon: -51.164, blurb: "avaliação rápida" },
  { id: "doceria-ponto-doce-84", name: "Doceria Ponto Doce", category: "doceria", lat: -29.666, lon: -51.1283, blurb: "docinho pra alegrar o dia" },
  { id: "bicicletaria-duas-rodas-85", name: "Bicicletaria Duas Rodas", category: "bicicletaria", lat: -29.7797, lon: -51.1617, blurb: "aluguel de bike também" },
  { id: "pizzaria-forno-a-lenha-86", name: "Pizzaria Forno a Lenha", category: "pizzaria", lat: -29.6533, lon: -51.1726, blurb: "fatia avulsa também" },
  { id: "assistencia-ortopedica-apoio-total", name: "Assistência Ortopédica Apoio Total", category: "ortopedia", lat: -29.6634, lon: -50.9598, blurb: "conserto de cadeira de rodas" },
  { id: "loja-estilo-vale-88", name: "Loja Estilo Vale", category: "loja de roupas", lat: -29.5983, lon: -51.1545, blurb: "roupa boa e barata" },
  { id: "loja-point-da-moda", name: "Loja Point da Moda", category: "loja de roupas", lat: -29.7364, lon: -51.1462, blurb: "roupa boa e barata" },
  { id: "lavanderia-bem-lavado", name: "Lavanderia Bem Lavado", category: "lavanderia", lat: -29.7799, lon: -51.1527, blurb: "lavagem rápida self-service" },
  { id: "salao-vale-beleza", name: "Salão Vale Beleza", category: "salão de beleza", lat: -29.6303, lon: -50.9862, blurb: "encaixe rápido às vezes rola" },
  { id: "pizzaria-vale-pizza", name: "Pizzaria Vale Pizza", category: "pizzaria", lat: -29.8149, lon: -51.1265, blurb: "fatia avulsa também" },
  { id: "acougue-central-93", name: "Açougue Central", category: "açougue", lat: -29.7771, lon: -51.1223, blurb: "carne fresca, corte na hora" },
  { id: "restaurante-vale-grill", name: "Restaurante Vale Grill", category: "restaurante", lat: -29.6697, lon: -51.0693, blurb: "marmita e prato feito" },
  { id: "posto-ipiranga-do-bairro", name: "Posto Ipiranga do Bairro", category: "posto de gasolina", lat: -29.7708, lon: -51.1319, blurb: "banheiro limpo e loja de conveniência" },
  { id: "academia-movimento-96", name: "Academia Movimento", category: "academia", lat: -29.7852, lon: -51.1703, blurb: "aula experimental grátis" },
  { id: "bicicletaria-roda-livre-97", name: "Bicicletaria Roda Livre", category: "bicicletaria", lat: -29.7427, lon: -51.1271, blurb: "troca de câmara e ajuste de freio, rapidinho" },
  { id: "sorveteria-gelato-vale", name: "Sorveteria Gelato Vale", category: "sorveteria", lat: -29.6315, lon: -50.9736, blurb: "sorvete artesanal" },
  { id: "mercadinho-economia", name: "Mercadinho Economia", category: "mercado", lat: -29.7849, lon: -51.1642, blurb: "preço justo" },
  { id: "assistencia-ortopedica-apoio-total-100", name: "Assistência Ortopédica Apoio Total", category: "ortopedia", lat: -29.6226, lon: -50.9658, blurb: "conserto de cadeira de rodas" },
  { id: "posto-central-101", name: "Posto Central", category: "posto de gasolina", lat: -29.6542, lon: -51.1381, blurb: "banheiro limpo e loja de conveniência" },
  { id: "bicicletaria-roda-livre-102", name: "Bicicletaria Roda Livre", category: "bicicletaria", lat: -29.6778, lon: -51.0413, blurb: "aluguel de bike também" },
  { id: "doceria-doce-vale-103", name: "Doceria Doce Vale", category: "doceria", lat: -29.7943, lon: -51.1239, blurb: "docinho pra alegrar o dia" },
  { id: "mercado-economia", name: "Mercado Economia", category: "mercado", lat: -29.6958, lon: -51.1339, blurb: "bom pra uma comprinha rápida" },
  { id: "mercado-vale-fresco", name: "Mercado Vale Fresco", category: "mercado", lat: -29.641, lon: -51.1549, blurb: "preço justo" },
  { id: "oficina-mecanica-rapida-106", name: "Oficina Mecânica Rápida", category: "oficina mecânica", lat: -29.7857, lon: -51.1672, blurb: "revisão rápida, sem enrolação" },
  { id: "padaria-sabor-caseiro", name: "Padaria Sabor Caseiro", category: "padaria", lat: -29.6256, lon: -51.181, blurb: "pão quente saindo do forno" },
  { id: "padaria-trigo-dourado", name: "Padaria Trigo Dourado", category: "padaria", lat: -29.6759, lon: -51.1067, blurb: "pão quente saindo do forno" },
  { id: "bicicletaria-pedal-vale-109", name: "Bicicletaria Pedal Vale", category: "bicicletaria", lat: -29.654, lon: -51.152, blurb: "troca de câmara e ajuste de freio, rapidinho" },
  { id: "bicicletaria-pedal-vale-110", name: "Bicicletaria Pedal Vale", category: "bicicletaria", lat: -29.6472, lon: -50.966, blurb: "troca de câmara e ajuste de freio, rapidinho" },
  { id: "padaria-sabor-caseiro-111", name: "Padaria Sabor Caseiro", category: "padaria", lat: -29.6441, lon: -51.005, blurb: "pão quente saindo do forno" },
  { id: "pet-shop-cao-e-gato", name: "Pet Shop Cão e Gato", category: "pet shop", lat: -29.6558, lon: -51.1391, blurb: "ração e banho e tosa" },
  { id: "assistencia-ponto-celular", name: "Assistência Ponto Celular", category: "loja de celular", lat: -29.7809, lon: -51.16, blurb: "conserto rápido" },
  { id: "papelaria-escolar-114", name: "Papelaria Escolar", category: "papelaria", lat: -29.6682, lon: -51.1229, blurb: "material escolar e impressão" },
  { id: "otica-vale-visao", name: "Ótica Vale Visão", category: "ótica", lat: -29.6953, lon: -51.1422, blurb: "exame de vista rápido" },
  { id: "assistencia-tela-nova", name: "Assistência Tela Nova", category: "loja de celular", lat: -29.6778, lon: -51.1086, blurb: "conserto rápido" },
  { id: "acougue-central-117", name: "Açougue Central", category: "açougue", lat: -29.6854, lon: -51.2179, blurb: "carne fresca, corte na hora" },
  { id: "lanchonete-point", name: "Lanchonete Point", category: "lanchonete", lat: -29.684, lon: -51.0551, blurb: "suco natural também" },
  { id: "farmacia-popular", name: "Farmácia Popular", category: "farmácia", lat: -29.8057, lon: -51.1344, blurb: "tem manipulação também" },
  { id: "farmacia-central", name: "Farmácia Central", category: "farmácia", lat: -29.6752, lon: -51.1166, blurb: "24 horas" },
  { id: "clinica-odontologica-dente-sadio-121", name: "Clínica Odontológica Dente Sadio", category: "clínica odontológica", lat: -29.6546, lon: -51.147, blurb: "avaliação rápida" },
  { id: "ortopedia-vale-ortopedia", name: "Ortopedia Vale Ortopedia", category: "ortopedia", lat: -29.6686, lon: -51.0625, blurb: "conserto de cadeira de rodas" },
  { id: "papelaria-ponto-do-aluno-123", name: "Papelaria Ponto do Aluno", category: "papelaria", lat: -29.6482, lon: -51.1543, blurb: "cópia rápida" },
  { id: "padaria-do-bairro", name: "Padaria do Bairro", category: "padaria", lat: -29.6681, lon: -51.1097, blurb: "salgados fresquinhos" },
  { id: "loja-point-da-moda-125", name: "Loja Point da Moda", category: "loja de roupas", lat: -29.6517, lon: -50.9955, blurb: "roupa boa e barata" },
  { id: "conveniencia-24h-vale-126", name: "Conveniência 24h Vale", category: "loja de conveniência", lat: -29.6916, lon: -51.1506, blurb: "aberto até tarde" },
  { id: "acougue-do-gaucho-127", name: "Açougue do Gaúcho", category: "açougue", lat: -29.7747, lon: -51.1374, blurb: "carne fresca, corte na hora" },
  { id: "bicicletaria-duas-rodas-128", name: "Bicicletaria Duas Rodas", category: "bicicletaria", lat: -29.7646, lon: -51.1319, blurb: "troca de câmara e ajuste de freio, rapidinho" },
  { id: "loja-veste-bem", name: "Loja Veste Bem", category: "loja de roupas", lat: -29.7705, lon: -51.1487, blurb: "roupa boa e barata" },
  { id: "academia-forca-total-130", name: "Academia Força Total", category: "academia", lat: -29.6283, lon: -50.9679, blurb: "aula experimental grátis" },
  { id: "acougue-vale-carnes", name: "Açougue Vale Carnes", category: "açougue", lat: -29.7779, lon: -51.1442, blurb: "carne fresca, corte na hora" },
  { id: "hortifruti-verde-vale-132", name: "Hortifruti Verde Vale", category: "hortifruti", lat: -29.6622, lon: -51.1904, blurb: "fruta e verdura fresquinha" },
  { id: "assistencia-ortopedica-equilibrio", name: "Assistência Ortopédica Equilíbrio", category: "ortopedia", lat: -29.6941, lon: -51.1121, blurb: "conserto de cadeira de rodas" },
  { id: "otica-vale-visao-134", name: "Ótica Vale Visão", category: "ótica", lat: -29.8072, lon: -51.1634, blurb: "exame de vista rápido" },
  { id: "lanchonete-central-135", name: "Lanchonete Central", category: "lanchonete", lat: -29.5954, lon: -51.1527, blurb: "lanche rápido no caminho" },
  { id: "restaurante-cantina-do-bairro-136", name: "Restaurante Cantina do Bairro", category: "restaurante", lat: -29.6997, lon: -51.1315, blurb: "marmita e prato feito" },
  { id: "assistencia-conserta-ja-137", name: "Assistência Conserta Já", category: "loja de celular", lat: -29.7049, lon: -51.2608, blurb: "conserto rápido" },
  { id: "barbearia-corte-certo-138", name: "Barbearia Corte Certo", category: "barbearia", lat: -29.6054, lon: -51.1798, blurb: "corte rápido, sem hora marcada" },
  { id: "pet-shop-cao-e-gato-139", name: "Pet Shop Cão e Gato", category: "pet shop", lat: -29.7643, lon: -51.1388, blurb: "atendimento rápido" },
  { id: "cafe-ceu-da-boca", name: "Café Céu da Boca", category: "café", lat: -29.6065, lon: -51.1722, blurb: "cafezinho bom e barato" },
  { id: "hortifruti-horta-fresca-141", name: "Hortifruti Horta Fresca", category: "hortifruti", lat: -29.7762, lon: -51.1681, blurb: "fruta e verdura fresquinha" },
  { id: "posto-rodovia", name: "Posto Rodovia", category: "posto de gasolina", lat: -29.7826, lon: -51.1662, blurb: "banheiro limpo e loja de conveniência" },
  { id: "academia-forca-total-143", name: "Academia Força Total", category: "academia", lat: -29.6709, lon: -51.1058, blurb: "aula experimental grátis" },
  { id: "cafe-bom-dia", name: "Café Bom Dia", category: "café", lat: -29.7502, lon: -51.1338, blurb: "cafezinho bom e barato" },
  { id: "oficina-mecanica-rapida-145", name: "Oficina Mecânica Rápida", category: "oficina mecânica", lat: -29.7935, lon: -51.1648, blurb: "revisão rápida, sem enrolação" },
  { id: "papelaria-escolar-146", name: "Papelaria Escolar", category: "papelaria", lat: -29.6045, lon: -51.1394, blurb: "material escolar e impressão" },
  { id: "restaurante-fogo-brando", name: "Restaurante Fogo Brando", category: "restaurante", lat: -29.8061, lon: -51.1625, blurb: "bom pra um almoço rápido" },
  { id: "padaria-relogio", name: "Padaria Relógio", category: "padaria", lat: -29.654, lon: -51.1207, blurb: "pão quente saindo do forno" },
  { id: "academia-vale-fit-149", name: "Academia Vale Fit", category: "academia", lat: -29.6231, lon: -50.9781, blurb: "aula experimental grátis" },
  { id: "acougue-boi-gordo-150", name: "Açougue Boi Gordo", category: "açougue", lat: -29.6532, lon: -51.1716, blurb: "carne fresca, corte na hora" },
  { id: "restaurante-cantina-do-bairro-151", name: "Restaurante Cantina do Bairro", category: "restaurante", lat: -29.6579, lon: -51.0063, blurb: "marmita e prato feito" },
  { id: "cafe-aroma-152", name: "Café Aroma", category: "café", lat: -29.7401, lon: -51.1258, blurb: "um café rápido no caminho" },
  { id: "acougue-do-gaucho-153", name: "Açougue do Gaúcho", category: "açougue", lat: -29.8107, lon: -51.1461, blurb: "carne fresca, corte na hora" },
  { id: "academia-movimento-154", name: "Academia Movimento", category: "academia", lat: -29.695, lon: -51.0524, blurb: "aula experimental grátis" },
  { id: "floricultura-jardim-vale-155", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.6909, lon: -51.1433, blurb: "flores frescas todo dia" },
  { id: "pizzaria-point-da-pizza-156", name: "Pizzaria Point da Pizza", category: "pizzaria", lat: -29.6586, lon: -51.1388, blurb: "fatia avulsa também" },
  { id: "banca-vale-jornal", name: "Banca Vale Jornal", category: "banca de jornal", lat: -29.6011, lon: -51.1536, blurb: "revista e jornal do dia" },
  { id: "pizzaria-point-da-pizza-158", name: "Pizzaria Point da Pizza", category: "pizzaria", lat: -29.6877, lon: -51.1379, blurb: "fatia avulsa também" },
  { id: "hortifruti-do-bairro", name: "Hortifruti do Bairro", category: "hortifruti", lat: -29.6565, lon: -51.1495, blurb: "fruta e verdura fresquinha" },
  { id: "posto-central-160", name: "Posto Central", category: "posto de gasolina", lat: -29.6548, lon: -51.04, blurb: "banheiro limpo e loja de conveniência" },
  { id: "sorveteria-bola-de-neve-161", name: "Sorveteria Bola de Neve", category: "sorveteria", lat: -29.6688, lon: -51.133, blurb: "sorvete artesanal" },
  { id: "lavanderia-self-service", name: "Lavanderia Self Service", category: "lavanderia", lat: -29.6688, lon: -51.1528, blurb: "lavagem rápida self-service" },
  { id: "barbearia-vale-barber", name: "Barbearia Vale Barber", category: "barbearia", lat: -29.7947, lon: -51.144, blurb: "corte rápido, sem hora marcada" },
  { id: "salao-beleza-pura-164", name: "Salão Beleza Pura", category: "salão de beleza", lat: -29.6765, lon: -51.1428, blurb: "corte e escova" },
  { id: "bicicletaria-duas-rodas-165", name: "Bicicletaria Duas Rodas", category: "bicicletaria", lat: -29.6937, lon: -51.1523, blurb: "troca de câmara e ajuste de freio, rapidinho" },
  { id: "padaria-nova-esperanca", name: "Padaria Nova Esperança", category: "padaria", lat: -29.7446, lon: -51.1481, blurb: "boa pra um café da manhã rápido" },
  { id: "conveniencia-sempre-aberto-167", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.724, lon: -51.2563, blurb: "aberto até tarde" },
  { id: "livraria-vale-do-livro-168", name: "Livraria Vale do Livro", category: "livraria", lat: -29.6298, lon: -50.9811, blurb: "boa pra matar um tempo esperando o ônibus" },
  { id: "mercado-bom-preco", name: "Mercado Bom Preço", category: "mercado", lat: -29.7013, lon: -51.1111, blurb: "bom pra uma comprinha rápida" },
  { id: "papelaria-ponto-do-aluno-170", name: "Papelaria Ponto do Aluno", category: "papelaria", lat: -29.6926, lon: -51.1077, blurb: "cópia rápida" },
  { id: "livraria-capitulo", name: "Livraria Capítulo", category: "livraria", lat: -29.6895, lon: -51.0688, blurb: "boa pra matar um tempo esperando o ônibus" },
  { id: "cafeteria-vale-do-cafe", name: "Cafeteria Vale do Café", category: "café", lat: -29.627, lon: -51.1715, blurb: "cafezinho bom e barato" },
  { id: "banca-noticia-ja-173", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7564, lon: -51.1609, blurb: "revista e jornal do dia" },
  { id: "papelaria-escolar-174", name: "Papelaria Escolar", category: "papelaria", lat: -29.6764, lon: -51.2219, blurb: "material escolar e impressão" },
  { id: "assistencia-tela-nova-175", name: "Assistência Tela Nova", category: "loja de celular", lat: -29.8048, lon: -51.1433, blurb: "conserto rápido" },
  { id: "barbearia-do-seu-ze-176", name: "Barbearia do Seu Zé", category: "barbearia", lat: -29.6629, lon: -51.0789, blurb: "corte rápido, sem hora marcada" },
  { id: "salao-beleza-pura-177", name: "Salão Beleza Pura", category: "salão de beleza", lat: -29.693, lon: -51.1412, blurb: "encaixe rápido às vezes rola" },
  { id: "loja-conserta-ja", name: "Loja Conserta Já", category: "loja de celular", lat: -29.6451, lon: -51.1785, blurb: "troca de tela na hora" },
  { id: "acougue-boi-gordo-179", name: "Açougue Boi Gordo", category: "açougue", lat: -29.6512, lon: -50.9602, blurb: "carne fresca, corte na hora" },
  { id: "doceria-doce-vale-180", name: "Doceria Doce Vale", category: "doceria", lat: -29.6593, lon: -50.9764, blurb: "docinho pra alegrar o dia" },
  { id: "otica-central", name: "Ótica Central", category: "ótica", lat: -29.7881, lon: -51.1683, blurb: "exame de vista rápido" },
  { id: "farmacia-central-182", name: "Farmácia Central", category: "farmácia", lat: -29.7794, lon: -51.1668, blurb: "tem manipulação também" },
  { id: "cafe-vale-do-cafe", name: "Café Vale do Café", category: "café", lat: -29.7003, lon: -51.1122, blurb: "cafezinho bom e barato" },
  { id: "lanchonete-esquina-184", name: "Lanchonete Esquina", category: "lanchonete", lat: -29.7682, lon: -51.1369, blurb: "suco natural também" },
  { id: "farmacia-nova-vida", name: "Farmácia Nova Vida", category: "farmácia", lat: -29.6331, lon: -51.1911, blurb: "farmácia acessível, caso precise de algo" },
  { id: "bicicletaria-roda-livre-186", name: "Bicicletaria Roda Livre", category: "bicicletaria", lat: -29.7611, lon: -51.1648, blurb: "aluguel de bike também" },
  { id: "conveniencia-sempre-aberto-187", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.5871, lon: -51.1445, blurb: "aberto até tarde" },
  { id: "papelaria-ponto-do-aluno-188", name: "Papelaria Ponto do Aluno", category: "papelaria", lat: -29.7828, lon: -51.1615, blurb: "cópia rápida" },
  { id: "papelaria-escolar-189", name: "Papelaria Escolar", category: "papelaria", lat: -29.6688, lon: -51.1233, blurb: "material escolar e impressão" },
  { id: "bicicletaria-ciclo-bom-190", name: "Bicicletaria Ciclo Bom", category: "bicicletaria", lat: -29.6809, lon: -51.1081, blurb: "aluguel de bike também" },
  { id: "clinica-odontologica-sorriso-vale", name: "Clínica Odontológica Sorriso Vale", category: "clínica odontológica", lat: -29.6534, lon: -51.0878, blurb: "avaliação rápida" },
  { id: "salao-beleza-pura-192", name: "Salão Beleza Pura", category: "salão de beleza", lat: -29.8093, lon: -51.1622, blurb: "corte e escova" },
  { id: "cafeteria-ceu-da-boca", name: "Cafeteria Céu da Boca", category: "café", lat: -29.7376, lon: -51.1364, blurb: "um café rápido no caminho" },
  { id: "farmacia-central-194", name: "Farmácia Central", category: "farmácia", lat: -29.6555, lon: -51.0805, blurb: "farmácia acessível, caso precise de algo" },
  { id: "restaurante-sabor-caseiro", name: "Restaurante Sabor Caseiro", category: "restaurante", lat: -29.688, lon: -51.1437, blurb: "marmita e prato feito" },
  { id: "acougue-central-196", name: "Açougue Central", category: "açougue", lat: -29.7901, lon: -51.1378, blurb: "carne fresca, corte na hora" },
  { id: "academia-forca-total-197", name: "Academia Força Total", category: "academia", lat: -29.6704, lon: -51.0574, blurb: "aula experimental grátis" },
  { id: "hortifruti-verde-vale-198", name: "Hortifruti Verde Vale", category: "hortifruti", lat: -29.68, lon: -51.1162, blurb: "fruta e verdura fresquinha" },
  { id: "restaurante-vale-grill-199", name: "Restaurante Vale Grill", category: "restaurante", lat: -29.6577, lon: -51.0012, blurb: "marmita e prato feito" },
  { id: "posto-central-200", name: "Posto Central", category: "posto de gasolina", lat: -29.7607, lon: -51.1249, blurb: "banheiro limpo e loja de conveniência" },
  { id: "academia-corpo-ativo-201", name: "Academia Corpo Ativo", category: "academia", lat: -29.7639, lon: -51.1535, blurb: "aula experimental grátis" },
  { id: "doceria-doce-vale-202", name: "Doceria Doce Vale", category: "doceria", lat: -29.6237, lon: -50.9814, blurb: "docinho pra alegrar o dia" },
  { id: "farmacia-sao-jose", name: "Farmácia São José", category: "farmácia", lat: -29.5827, lon: -51.1335, blurb: "24 horas" },
  { id: "oficina-mecanica-rapida-204", name: "Oficina Mecânica Rápida", category: "oficina mecânica", lat: -29.6462, lon: -50.9647, blurb: "revisão rápida, sem enrolação" },
  { id: "pizzaria-vale-pizza-205", name: "Pizzaria Vale Pizza", category: "pizzaria", lat: -29.6619, lon: -51.0598, blurb: "fatia avulsa também" },
  { id: "loja-conserta-ja-206", name: "Loja Conserta Já", category: "loja de celular", lat: -29.6838, lon: -51.1144, blurb: "troca de tela na hora" },
  { id: "sapataria-conserta-tudo-207", name: "Sapataria Conserta Tudo", category: "sapataria", lat: -29.6703, lon: -51.1693, blurb: "conserto de calçado na hora" },
  { id: "floricultura-petala", name: "Floricultura Pétala", category: "floricultura", lat: -29.6769, lon: -51.043, blurb: "flores frescas todo dia" },
  { id: "pizzaria-fatia-boa-209", name: "Pizzaria Fatia Boa", category: "pizzaria", lat: -29.6185, lon: -51.1381, blurb: "fatia avulsa também" },
  { id: "livraria-do-saber-210", name: "Livraria do Saber", category: "livraria", lat: -29.7892, lon: -51.1448, blurb: "tem seção de segunda mão" },
  { id: "mercadinho-economia-211", name: "Mercadinho Economia", category: "mercado", lat: -29.6218, lon: -50.9701, blurb: "bom pra uma comprinha rápida" },
  { id: "banca-do-centro", name: "Banca do Centro", category: "banca de jornal", lat: -29.7874, lon: -51.1548, blurb: "revista e jornal do dia" },
  { id: "banca-vale-jornal-213", name: "Banca Vale Jornal", category: "banca de jornal", lat: -29.6279, lon: -50.9949, blurb: "revista e jornal do dia" },
  { id: "pet-shop-amigo-fiel", name: "Pet Shop Amigo Fiel", category: "pet shop", lat: -29.6607, lon: -51.1304, blurb: "atendimento rápido" },
  { id: "banca-vale-jornal-215", name: "Banca Vale Jornal", category: "banca de jornal", lat: -29.6399, lon: -51.1815, blurb: "revista e jornal do dia" },
  { id: "barbearia-vale-barber-216", name: "Barbearia Vale Barber", category: "barbearia", lat: -29.6962, lon: -51.1502, blurb: "corte rápido, sem hora marcada" },
  { id: "posto-rodovia-217", name: "Posto Rodovia", category: "posto de gasolina", lat: -29.6647, lon: -51.155, blurb: "banheiro limpo e loja de conveniência" },
  { id: "bicicletaria-pedal-vale-218", name: "Bicicletaria Pedal Vale", category: "bicicletaria", lat: -29.672, lon: -51.1301, blurb: "aluguel de bike também" },
  { id: "bicicletaria-pedal-vale-219", name: "Bicicletaria Pedal Vale", category: "bicicletaria", lat: -29.7992, lon: -51.1542, blurb: "aluguel de bike também" },
  { id: "clinica-odontologica-sorriso-vale-220", name: "Clínica Odontológica Sorriso Vale", category: "clínica odontológica", lat: -29.7795, lon: -51.1366, blurb: "avaliação rápida" },
  { id: "floricultura-jardim-vale-221", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.6034, lon: -51.1637, blurb: "flores frescas todo dia" },
  { id: "mercadinho-do-ze", name: "Mercadinho do Zé", category: "mercado", lat: -29.7558, lon: -51.1467, blurb: "tem de tudo um pouco" },
  { id: "farmacia-vale-bem", name: "Farmácia Vale Bem", category: "farmácia", lat: -29.7904, lon: -51.1654, blurb: "farmácia acessível, caso precise de algo" },
  { id: "posto-ipiranga-do-bairro-224", name: "Posto Ipiranga do Bairro", category: "posto de gasolina", lat: -29.6989, lon: -51.0669, blurb: "banheiro limpo e loja de conveniência" },
  { id: "hortifruti-fruta-boa", name: "Hortifruti Fruta Boa", category: "hortifruti", lat: -29.6923, lon: -51.1217, blurb: "fruta e verdura fresquinha" },
  { id: "floricultura-flor-de-lis-226", name: "Floricultura Flor de Lis", category: "floricultura", lat: -29.8083, lon: -51.1302, blurb: "flores frescas todo dia" },
  { id: "posto-vale-combustivel", name: "Posto Vale Combustível", category: "posto de gasolina", lat: -29.6026, lon: -51.1467, blurb: "banheiro limpo e loja de conveniência" },
  { id: "banca-noticia-ja-228", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7814, lon: -51.1329, blurb: "revista e jornal do dia" },
  { id: "hortifruti-horta-fresca-229", name: "Hortifruti Horta Fresca", category: "hortifruti", lat: -29.6463, lon: -51.0078, blurb: "fruta e verdura fresquinha" },
  { id: "doceria-guloseima-230", name: "Doceria Guloseima", category: "doceria", lat: -29.7586, lon: -51.1314, blurb: "docinho pra alegrar o dia" },
  { id: "floricultura-petala-231", name: "Floricultura Pétala", category: "floricultura", lat: -29.6647, lon: -51.1294, blurb: "flores frescas todo dia" },
  { id: "academia-movimento-232", name: "Academia Movimento", category: "academia", lat: -29.6481, lon: -50.9955, blurb: "aula experimental grátis" },
  { id: "restaurante-fogo-brando-233", name: "Restaurante Fogo Brando", category: "restaurante", lat: -29.6341, lon: -51.1931, blurb: "marmita e prato feito" },
  { id: "otica-vale-visao-234", name: "Ótica Vale Visão", category: "ótica", lat: -29.7833, lon: -51.167, blurb: "exame de vista rápido" },
  { id: "pizzaria-fatia-boa-235", name: "Pizzaria Fatia Boa", category: "pizzaria", lat: -29.6241, lon: -50.982, blurb: "fatia avulsa também" },
  { id: "bicicletaria-pedal-vale-236", name: "Bicicletaria Pedal Vale", category: "bicicletaria", lat: -29.7827, lon: -51.1245, blurb: "aluguel de bike também" },
  { id: "pizzaria-vale-pizza-237", name: "Pizzaria Vale Pizza", category: "pizzaria", lat: -29.6709, lon: -51.1273, blurb: "fatia avulsa também" },
  { id: "acougue-central-238", name: "Açougue Central", category: "açougue", lat: -29.6884, lon: -51.1164, blurb: "carne fresca, corte na hora" },
  { id: "farmacia-central-239", name: "Farmácia Central", category: "farmácia", lat: -29.6669, lon: -51.1579, blurb: "farmácia acessível, caso precise de algo" },
  { id: "acougue-central-240", name: "Açougue Central", category: "açougue", lat: -29.6613, lon: -51.0416, blurb: "carne fresca, corte na hora" },
  { id: "floricultura-petala-241", name: "Floricultura Pétala", category: "floricultura", lat: -29.6769, lon: -51.0444, blurb: "flores frescas todo dia" },
  { id: "sorveteria-sabor-gelado-242", name: "Sorveteria Sabor Gelado", category: "sorveteria", lat: -29.5931, lon: -51.1819, blurb: "sorvete artesanal" },
  { id: "salao-espaco-vaidosa-243", name: "Salão Espaço Vaidosa", category: "salão de beleza", lat: -29.7914, lon: -51.1344, blurb: "corte e escova" },
  { id: "banca-noticia-ja-244", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.6778, lon: -51.0462, blurb: "revista e jornal do dia" },
  { id: "banca-do-centro-245", name: "Banca do Centro", category: "banca de jornal", lat: -29.752, lon: -51.1332, blurb: "revista e jornal do dia" },
  { id: "sapataria-conserta-tudo-246", name: "Sapataria Conserta Tudo", category: "sapataria", lat: -29.8035, lon: -51.1484, blurb: "troca de sola rápida" },
  { id: "sorveteria-gelato-vale-247", name: "Sorveteria Gelato Vale", category: "sorveteria", lat: -29.7451, lon: -51.1278, blurb: "sorvete artesanal" },
  { id: "banca-noticia-ja-248", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7396, lon: -51.162, blurb: "revista e jornal do dia" },
  { id: "lavanderia-rapida-249", name: "Lavanderia Rápida", category: "lavanderia", lat: -29.6852, lon: -51.121, blurb: "lavagem rápida self-service" },
  { id: "oficina-freio-e-cia", name: "Oficina Freio e Cia", category: "oficina mecânica", lat: -29.7877, lon: -51.1503, blurb: "revisão rápida, sem enrolação" },
  { id: "doceria-acucar", name: "Doceria Açúcar", category: "doceria", lat: -29.6688, lon: -51.1482, blurb: "docinho pra alegrar o dia" },
  { id: "salao-espaco-vaidosa-252", name: "Salão Espaço Vaidosa", category: "salão de beleza", lat: -29.6691, lon: -51.1357, blurb: "encaixe rápido às vezes rola" },
  { id: "papelaria-central-253", name: "Papelaria Central", category: "papelaria", lat: -29.5784, lon: -51.1768, blurb: "cópia rápida" },
  { id: "ortopedia-equilibrio", name: "Ortopedia Equilíbrio", category: "ortopedia", lat: -29.6503, lon: -50.9787, blurb: "conserto de cadeira de rodas" },
  { id: "loja-estilo-vale-255", name: "Loja Estilo Vale", category: "loja de roupas", lat: -29.7691, lon: -51.1488, blurb: "roupa boa e barata" },
  { id: "pizzaria-forno-a-lenha-256", name: "Pizzaria Forno a Lenha", category: "pizzaria", lat: -29.6753, lon: -51.1139, blurb: "fatia avulsa também" },
  { id: "cafeteria-grao-bom", name: "Cafeteria Grão Bom", category: "café", lat: -29.6215, lon: -50.9724, blurb: "cafezinho bom e barato" },
  { id: "sorveteria-point-do-sorvete-258", name: "Sorveteria Point do Sorvete", category: "sorveteria", lat: -29.7693, lon: -51.1415, blurb: "sorvete artesanal" },
  { id: "floricultura-jardim-vale-259", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.6764, lon: -51.1249, blurb: "flores frescas todo dia" },
  { id: "floricultura-jardim-vale-260", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.662, lon: -51.1371, blurb: "flores frescas todo dia" },
  { id: "banca-noticia-ja-261", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.6685, lon: -51.1347, blurb: "revista e jornal do dia" },
  { id: "restaurante-cantina-do-bairro-262", name: "Restaurante Cantina do Bairro", category: "restaurante", lat: -29.6161, lon: -50.9814, blurb: "marmita e prato feito" },
  { id: "papelaria-central-263", name: "Papelaria Central", category: "papelaria", lat: -29.6789, lon: -51.1244, blurb: "cópia rápida" },
  { id: "floricultura-buque-264", name: "Floricultura Buquê", category: "floricultura", lat: -29.7586, lon: -51.1543, blurb: "flores frescas todo dia" },
  { id: "barbearia-navalha-de-ouro", name: "Barbearia Navalha de Ouro", category: "barbearia", lat: -29.6611, lon: -51.1448, blurb: "corte rápido, sem hora marcada" },
  { id: "salao-charme-266", name: "Salão Charme", category: "salão de beleza", lat: -29.6045, lon: -51.1459, blurb: "encaixe rápido às vezes rola" },
  { id: "mercado-bom-preco-267", name: "Mercado Bom Preço", category: "mercado", lat: -29.6344, lon: -51.0046, blurb: "bom pra uma comprinha rápida" },
  { id: "papelaria-vale-papel-268", name: "Papelaria Vale Papel", category: "papelaria", lat: -29.814, lon: -51.1667, blurb: "cópia rápida" },
  { id: "hortifruti-horta-fresca-269", name: "Hortifruti Horta Fresca", category: "hortifruti", lat: -29.6721, lon: -51.1575, blurb: "fruta e verdura fresquinha" },
  { id: "banca-vale-jornal-270", name: "Banca Vale Jornal", category: "banca de jornal", lat: -29.6939, lon: -51.1454, blurb: "revista e jornal do dia" },
  { id: "cafe-ceu-da-boca-271", name: "Café Céu da Boca", category: "café", lat: -29.7543, lon: -51.1653, blurb: "um café rápido no caminho" },
  { id: "clinica-odontologica-odonto-bem-272", name: "Clínica Odontológica Odonto Bem", category: "clínica odontológica", lat: -29.6166, lon: -51.1483, blurb: "avaliação rápida" },
  { id: "oficina-freio-e-cia-273", name: "Oficina Freio e Cia", category: "oficina mecânica", lat: -29.7783, lon: -51.1417, blurb: "revisão rápida, sem enrolação" },
  { id: "assistencia-ortopedica-vale-ortopedia", name: "Assistência Ortopédica Vale Ortopedia", category: "ortopedia", lat: -29.6709, lon: -51.135, blurb: "ajuste e manutenção de próteses e órteses" },
  { id: "conveniencia-sempre-aberto-275", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.6993, lon: -51.0479, blurb: "aberto até tarde" },
  { id: "mercadinho-bom-preco-276", name: "Mercadinho Bom Preço", category: "mercado", lat: -29.6764, lon: -51.134, blurb: "bom pra uma comprinha rápida" },
  { id: "academia-movimento-277", name: "Academia Movimento", category: "academia", lat: -29.7382, lon: -51.145, blurb: "aula experimental grátis" },
  { id: "lavanderia-self-service-278", name: "Lavanderia Self Service", category: "lavanderia", lat: -29.6982, lon: -51.061, blurb: "lavagem rápida self-service" },
  { id: "banca-noticia-ja-279", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7668, lon: -51.1649, blurb: "revista e jornal do dia" },
  { id: "hortifruti-fruta-boa-280", name: "Hortifruti Fruta Boa", category: "hortifruti", lat: -29.6328, lon: -51.1498, blurb: "fruta e verdura fresquinha" },
  { id: "sapataria-conserta-tudo-281", name: "Sapataria Conserta Tudo", category: "sapataria", lat: -29.7961, lon: -51.1552, blurb: "conserto de calçado na hora" },
  { id: "lavanderia-vale-limpo-282", name: "Lavanderia Vale Limpo", category: "lavanderia", lat: -29.6296, lon: -50.9641, blurb: "lavagem rápida self-service" },
  { id: "posto-central-283", name: "Posto Central", category: "posto de gasolina", lat: -29.6577, lon: -51.1948, blurb: "banheiro limpo e loja de conveniência" },
  { id: "mercadinho-do-ze-284", name: "Mercadinho do Zé", category: "mercado", lat: -29.6945, lon: -51.1198, blurb: "preço justo" },
  { id: "floricultura-jardim-vale-285", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.5925, lon: -51.1578, blurb: "flores frescas todo dia" },
  { id: "cafeteria-bom-dia", name: "Cafeteria Bom Dia", category: "café", lat: -29.6941, lon: -51.1413, blurb: "wifi de graça pra esperar" },
  { id: "posto-central-287", name: "Posto Central", category: "posto de gasolina", lat: -29.7947, lon: -51.1296, blurb: "banheiro limpo e loja de conveniência" },
  { id: "padaria-trigo-dourado-288", name: "Padaria Trigo Dourado", category: "padaria", lat: -29.6802, lon: -51.0657, blurb: "salgados fresquinhos" },
  { id: "salao-vale-beleza-289", name: "Salão Vale Beleza", category: "salão de beleza", lat: -29.629, lon: -50.9785, blurb: "encaixe rápido às vezes rola" },
  { id: "pet-shop-amigo-fiel-290", name: "Pet Shop Amigo Fiel", category: "pet shop", lat: -29.6255, lon: -51.1989, blurb: "ração e banho e tosa" },
  { id: "pet-shop-vale-pet", name: "Pet Shop Vale Pet", category: "pet shop", lat: -29.6987, lon: -51.1367, blurb: "ração e banho e tosa" },
  { id: "clinica-odontologica-sorriso-vale-292", name: "Clínica Odontológica Sorriso Vale", category: "clínica odontológica", lat: -29.6694, lon: -51.1661, blurb: "avaliação rápida" },
  { id: "oficina-do-marcao-293", name: "Oficina do Marcão", category: "oficina mecânica", lat: -29.7763, lon: -51.1421, blurb: "revisão rápida, sem enrolação" },
  { id: "hortifruti-verde-vale-294", name: "Hortifruti Verde Vale", category: "hortifruti", lat: -29.7145, lon: -51.2512, blurb: "fruta e verdura fresquinha" },
  { id: "sapataria-conserta-tudo-295", name: "Sapataria Conserta Tudo", category: "sapataria", lat: -29.7743, lon: -51.1443, blurb: "troca de sola rápida" },
  { id: "barbearia-do-seu-ze-296", name: "Barbearia do Seu Zé", category: "barbearia", lat: -29.6362, lon: -50.9608, blurb: "corte rápido, sem hora marcada" },
  { id: "livraria-vale-do-livro-297", name: "Livraria Vale do Livro", category: "livraria", lat: -29.6921, lon: -51.1484, blurb: "boa pra matar um tempo esperando o ônibus" },
  { id: "pet-shop-cao-e-gato-298", name: "Pet Shop Cão e Gato", category: "pet shop", lat: -29.6869, lon: -51.1551, blurb: "atendimento rápido" },
  { id: "oficina-mecanica-rapida-299", name: "Oficina Mecânica Rápida", category: "oficina mecânica", lat: -29.7692, lon: -51.1562, blurb: "revisão rápida, sem enrolação" },
  { id: "banca-noticia-ja-300", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7601, lon: -51.1293, blurb: "revista e jornal do dia" },
  { id: "livraria-vale-do-livro-301", name: "Livraria Vale do Livro", category: "livraria", lat: -29.7932, lon: -51.1504, blurb: "boa pra matar um tempo esperando o ônibus" },
  { id: "lanchonete-esquina-302", name: "Lanchonete Esquina", category: "lanchonete", lat: -29.6521, lon: -50.975, blurb: "suco natural também" },
  { id: "barbearia-corte-certo-303", name: "Barbearia Corte Certo", category: "barbearia", lat: -29.6137, lon: -51.1455, blurb: "corte rápido, sem hora marcada" },
  { id: "doceria-acucar-304", name: "Doceria Açúcar", category: "doceria", lat: -29.693, lon: -51.0506, blurb: "docinho pra alegrar o dia" },
  { id: "otica-clara-305", name: "Ótica Clara", category: "ótica", lat: -29.7709, lon: -51.1652, blurb: "exame de vista rápido" },
  { id: "banca-do-centro-306", name: "Banca do Centro", category: "banca de jornal", lat: -29.8146, lon: -51.1578, blurb: "revista e jornal do dia" },
  { id: "pet-shop-bicho-feliz", name: "Pet Shop Bicho Feliz", category: "pet shop", lat: -29.6526, lon: -50.9964, blurb: "atendimento rápido" },
  { id: "posto-rodovia-308", name: "Posto Rodovia", category: "posto de gasolina", lat: -29.698, lon: -51.1325, blurb: "banheiro limpo e loja de conveniência" },
  { id: "padaria-pao-nosso-309", name: "Padaria Pão Nosso", category: "padaria", lat: -29.6788, lon: -51.1495, blurb: "boa pra um café da manhã rápido" },
  { id: "acougue-do-gaucho-310", name: "Açougue do Gaúcho", category: "açougue", lat: -29.8095, lon: -51.1417, blurb: "carne fresca, corte na hora" },
  { id: "academia-movimento-311", name: "Academia Movimento", category: "academia", lat: -29.6597, lon: -51.1512, blurb: "aula experimental grátis" },
  { id: "clinica-odontologica-odonto-bem-312", name: "Clínica Odontológica Odonto Bem", category: "clínica odontológica", lat: -29.7834, lon: -51.1636, blurb: "avaliação rápida" },
  { id: "livraria-capitulo-313", name: "Livraria Capítulo", category: "livraria", lat: -29.6809, lon: -51.0877, blurb: "tem seção de segunda mão" },
  { id: "livraria-do-saber-314", name: "Livraria do Saber", category: "livraria", lat: -29.6391, lon: -50.981, blurb: "tem seção de segunda mão" },
  { id: "bicicletaria-duas-rodas-315", name: "Bicicletaria Duas Rodas", category: "bicicletaria", lat: -29.6637, lon: -51.1192, blurb: "aluguel de bike também" },
  { id: "academia-corpo-ativo-316", name: "Academia Corpo Ativo", category: "academia", lat: -29.7846, lon: -51.1234, blurb: "aula experimental grátis" },
  { id: "academia-corpo-ativo-317", name: "Academia Corpo Ativo", category: "academia", lat: -29.6582, lon: -51.1512, blurb: "aula experimental grátis" },
  { id: "posto-rodovia-318", name: "Posto Rodovia", category: "posto de gasolina", lat: -29.6635, lon: -51.179, blurb: "banheiro limpo e loja de conveniência" },
  { id: "oficina-do-marcao-319", name: "Oficina do Marcão", category: "oficina mecânica", lat: -29.6896, lon: -51.1356, blurb: "revisão rápida, sem enrolação" },
  { id: "academia-corpo-ativo-320", name: "Academia Corpo Ativo", category: "academia", lat: -29.776, lon: -51.1447, blurb: "aula experimental grátis" },
  { id: "oficina-vale-motor", name: "Oficina Vale Motor", category: "oficina mecânica", lat: -29.7966, lon: -51.1645, blurb: "revisão rápida, sem enrolação" },
  { id: "banca-vale-jornal-322", name: "Banca Vale Jornal", category: "banca de jornal", lat: -29.6998, lon: -51.1295, blurb: "revista e jornal do dia" },
  { id: "salao-charme-323", name: "Salão Charme", category: "salão de beleza", lat: -29.6563, lon: -51.0874, blurb: "encaixe rápido às vezes rola" },
  { id: "otica-central-324", name: "Ótica Central", category: "ótica", lat: -29.6726, lon: -51.1498, blurb: "exame de vista rápido" },
  { id: "bicicletaria-pedal-vale-325", name: "Bicicletaria Pedal Vale", category: "bicicletaria", lat: -29.8014, lon: -51.15, blurb: "aluguel de bike também" },
  { id: "oficina-do-marcao-326", name: "Oficina do Marcão", category: "oficina mecânica", lat: -29.7364, lon: -51.1454, blurb: "revisão rápida, sem enrolação" },
  { id: "restaurante-vale-grill-327", name: "Restaurante Vale Grill", category: "restaurante", lat: -29.605, lon: -51.1799, blurb: "marmita e prato feito" },
  { id: "otica-clara-328", name: "Ótica Clara", category: "ótica", lat: -29.6636, lon: -51.135, blurb: "conserto de óculos na hora" },
  { id: "academia-corpo-ativo-329", name: "Academia Corpo Ativo", category: "academia", lat: -29.6575, lon: -51.1406, blurb: "aula experimental grátis" },
  { id: "oficina-do-marcao-330", name: "Oficina do Marcão", category: "oficina mecânica", lat: -29.7529, lon: -51.1706, blurb: "revisão rápida, sem enrolação" },
  { id: "oficina-vale-motor-331", name: "Oficina Vale Motor", category: "oficina mecânica", lat: -29.6768, lon: -51.1355, blurb: "revisão rápida, sem enrolação" },
  { id: "sapataria-passo-firme", name: "Sapataria Passo Firme", category: "sapataria", lat: -29.6366, lon: -50.9772, blurb: "troca de sola rápida" },
  { id: "pizzaria-forno-a-lenha-333", name: "Pizzaria Forno a Lenha", category: "pizzaria", lat: -29.6762, lon: -51.1361, blurb: "fatia avulsa também" },
  { id: "mercadinho-do-ze-334", name: "Mercadinho do Zé", category: "mercado", lat: -29.6726, lon: -51.1351, blurb: "tem de tudo um pouco" },
  { id: "loja-ponto-celular", name: "Loja Ponto Celular", category: "loja de celular", lat: -29.7835, lon: -51.1645, blurb: "troca de tela na hora" },
  { id: "livraria-vale-do-livro-336", name: "Livraria Vale do Livro", category: "livraria", lat: -29.6352, lon: -50.9955, blurb: "boa pra matar um tempo esperando o ônibus" },
  { id: "oficina-do-marcao-337", name: "Oficina do Marcão", category: "oficina mecânica", lat: -29.7924, lon: -51.1569, blurb: "revisão rápida, sem enrolação" },
  { id: "doceria-acucar-338", name: "Doceria Açúcar", category: "doceria", lat: -29.7482, lon: -51.1525, blurb: "docinho pra alegrar o dia" },
  { id: "floricultura-jardim-vale-339", name: "Floricultura Jardim Vale", category: "floricultura", lat: -29.7913, lon: -51.1399, blurb: "flores frescas todo dia" },
  { id: "pet-shop-amigo-fiel-340", name: "Pet Shop Amigo Fiel", category: "pet shop", lat: -29.7704, lon: -51.1455, blurb: "ração e banho e tosa" },
  { id: "loja-veste-bem-341", name: "Loja Veste Bem", category: "loja de roupas", lat: -29.6425, lon: -50.9778, blurb: "roupa boa e barata" },
  { id: "doceria-ponto-doce-342", name: "Doceria Ponto Doce", category: "doceria", lat: -29.6618, lon: -51.1203, blurb: "docinho pra alegrar o dia" },
  { id: "loja-veste-bem-343", name: "Loja Veste Bem", category: "loja de roupas", lat: -29.6587, lon: -51.1647, blurb: "roupa boa e barata" },
  { id: "conveniencia-sempre-aberto-344", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.7933, lon: -51.1498, blurb: "aberto até tarde" },
  { id: "ortopedia-equilibrio-345", name: "Ortopedia Equilíbrio", category: "ortopedia", lat: -29.675, lon: -51.1362, blurb: "ajuste e manutenção de próteses e órteses" },
  { id: "loja-tela-nova", name: "Loja Tela Nova", category: "loja de celular", lat: -29.7909, lon: -51.1414, blurb: "conserto rápido" },
  { id: "restaurante-sabor-caseiro-347", name: "Restaurante Sabor Caseiro", category: "restaurante", lat: -29.6992, lon: -51.0729, blurb: "bom pra um almoço rápido" },
  { id: "assistencia-vale-cell", name: "Assistência Vale Cell", category: "loja de celular", lat: -29.7666, lon: -51.1331, blurb: "conserto rápido" },
  { id: "salao-beleza-pura-349", name: "Salão Beleza Pura", category: "salão de beleza", lat: -29.7731, lon: -51.1223, blurb: "corte e escova" },
  { id: "cafeteria-bom-dia-350", name: "Cafeteria Bom Dia", category: "café", lat: -29.8058, lon: -51.1356, blurb: "wifi de graça pra esperar" },
  { id: "conveniencia-rapidinho-351", name: "Conveniência Rapidinho", category: "loja de conveniência", lat: -29.6435, lon: -50.9667, blurb: "aberto até tarde" },
  { id: "sorveteria-bola-de-neve-352", name: "Sorveteria Bola de Neve", category: "sorveteria", lat: -29.7662, lon: -51.1596, blurb: "sorvete artesanal" },
  { id: "loja-estilo-vale-353", name: "Loja Estilo Vale", category: "loja de roupas", lat: -29.6912, lon: -51.0523, blurb: "roupa boa e barata" },
  { id: "papelaria-ponto-do-aluno-354", name: "Papelaria Ponto do Aluno", category: "papelaria", lat: -29.7753, lon: -51.1695, blurb: "cópia rápida" },
  { id: "academia-forca-total-355", name: "Academia Força Total", category: "academia", lat: -29.758, lon: -51.1522, blurb: "aula experimental grátis" },
  { id: "sapataria-passo-firme-356", name: "Sapataria Passo Firme", category: "sapataria", lat: -29.6669, lon: -51.1244, blurb: "troca de sola rápida" },
  { id: "floricultura-petala-357", name: "Floricultura Pétala", category: "floricultura", lat: -29.6443, lon: -50.9602, blurb: "flores frescas todo dia" },
  { id: "clinica-odontologica-dente-sadio-358", name: "Clínica Odontológica Dente Sadio", category: "clínica odontológica", lat: -29.8148, lon: -51.1588, blurb: "avaliação rápida" },
  { id: "conveniencia-sempre-aberto-359", name: "Conveniência Sempre Aberto", category: "loja de conveniência", lat: -29.7537, lon: -51.142, blurb: "aberto até tarde" },
  { id: "floricultura-flor-de-lis-360", name: "Floricultura Flor de Lis", category: "floricultura", lat: -29.6721, lon: -51.1325, blurb: "flores frescas todo dia" },
  { id: "doceria-doce-vale-361", name: "Doceria Doce Vale", category: "doceria", lat: -29.6591, lon: -51.0684, blurb: "docinho pra alegrar o dia" },
  { id: "sapataria-conserta-tudo-362", name: "Sapataria Conserta Tudo", category: "sapataria", lat: -29.7661, lon: -51.1458, blurb: "conserto de calçado na hora" },
  { id: "banca-noticia-ja-363", name: "Banca Notícia Já", category: "banca de jornal", lat: -29.7359, lon: -51.1487, blurb: "revista e jornal do dia" },
  { id: "banca-vale-jornal-364", name: "Banca Vale Jornal", category: "banca de jornal", lat: -29.75, lon: -51.1721, blurb: "revista e jornal do dia" },
  { id: "pet-shop-cao-e-gato-365", name: "Pet Shop Cão e Gato", category: "pet shop", lat: -29.8068, lon: -51.1298, blurb: "ração e banho e tosa" },
  { id: "otica-clara-366", name: "Ótica Clara", category: "ótica", lat: -29.7842, lon: -51.1263, blurb: "conserto de óculos na hora" },
  { id: "academia-forca-total-367", name: "Academia Força Total", category: "academia", lat: -29.7485, lon: -51.1266, blurb: "aula experimental grátis" },
  { id: "lanchonete-lanche-rapido", name: "Lanchonete Lanche Rápido", category: "lanchonete", lat: -29.7555, lon: -51.1348, blurb: "lanche rápido no caminho" },
  { id: "pet-shop-amigo-fiel-369", name: "Pet Shop Amigo Fiel", category: "pet shop", lat: -29.6694, lon: -51.1189, blurb: "ração e banho e tosa" },
  { id: "lanchonete-point-370", name: "Lanchonete Point", category: "lanchonete", lat: -29.8046, lon: -51.1662, blurb: "suco natural também" },
  { id: "livraria-vale-do-livro-371", name: "Livraria Vale do Livro", category: "livraria", lat: -29.6669, lon: -51.0554, blurb: "boa pra matar um tempo esperando o ônibus" },
  { id: "otica-foco-372", name: "Ótica Foco", category: "ótica", lat: -29.6545, lon: -51.1494, blurb: "conserto de óculos na hora" },
  { id: "oficina-do-marcao-373", name: "Oficina do Marcão", category: "oficina mecânica", lat: -29.7717, lon: -51.1396, blurb: "revisão rápida, sem enrolação" },
  { id: "floricultura-petala-374", name: "Floricultura Pétala", category: "floricultura", lat: -29.6744, lon: -51.0774, blurb: "flores frescas todo dia" },
  { id: "clinica-odontologica-sorriso-vale-375", name: "Clínica Odontológica Sorriso Vale", category: "clínica odontológica", lat: -29.743, lon: -51.1346, blurb: "avaliação rápida" },
  { id: "farmacia-nova-vida-376", name: "Farmácia Nova Vida", category: "farmácia", lat: -29.678, lon: -51.1127, blurb: "24 horas" },
  { id: "padaria-colonial", name: "Padaria Colonial", category: "padaria", lat: -29.6503, lon: -51.1824, blurb: "salgados fresquinhos" },
  { id: "padaria-sabor-caseiro-378", name: "Padaria Sabor Caseiro", category: "padaria", lat: -29.7799, lon: -51.1615, blurb: "pão quente saindo do forno" },
  { id: "padaria-relogio-379", name: "Padaria Relógio", category: "padaria", lat: -29.6668, lon: -51.1314, blurb: "salgados fresquinhos" },
  { id: "livraria-capitulo-380", name: "Livraria Capítulo", category: "livraria", lat: -29.7454, lon: -51.1285, blurb: "tem seção de segunda mão" },
  { id: "barbearia-vale-barber-381", name: "Barbearia Vale Barber", category: "barbearia", lat: -29.5752, lon: -51.167, blurb: "corte rápido, sem hora marcada" },
  { id: "papelaria-escolar-382", name: "Papelaria Escolar", category: "papelaria", lat: -29.6763, lon: -51.1098, blurb: "cópia rápida" },
  { id: "conveniencia-24h-vale-383", name: "Conveniência 24h Vale", category: "loja de conveniência", lat: -29.7851, lon: -51.1588, blurb: "aberto até tarde" },
  { id: "pizzaria-vale-pizza-384", name: "Pizzaria Vale Pizza", category: "pizzaria", lat: -29.6161, lon: -50.9876, blurb: "fatia avulsa também" },
  { id: "sorveteria-sabor-gelado-385", name: "Sorveteria Sabor Gelado", category: "sorveteria", lat: -29.6531, lon: -51.0738, blurb: "sorvete artesanal" },
  { id: "clinica-odontologica-odonto-bem-386", name: "Clínica Odontológica Odonto Bem", category: "clínica odontológica", lat: -29.7701, lon: -51.1528, blurb: "avaliação rápida" },
  { id: "hortifruti-fruta-boa-387", name: "Hortifruti Fruta Boa", category: "hortifruti", lat: -29.744, lon: -51.1597, blurb: "fruta e verdura fresquinha" },
  { id: "salao-beleza-pura-388", name: "Salão Beleza Pura", category: "salão de beleza", lat: -29.7784, lon: -51.132, blurb: "corte e escova" },
  { id: "lavanderia-self-service-389", name: "Lavanderia Self Service", category: "lavanderia", lat: -29.6375, lon: -51.1913, blurb: "lavagem rápida self-service" },
  { id: "lavanderia-self-service-390", name: "Lavanderia Self Service", category: "lavanderia", lat: -29.6027, lon: -51.1455, blurb: "lavagem rápida self-service" },
  { id: "conveniencia-rapidinho-391", name: "Conveniência Rapidinho", category: "loja de conveniência", lat: -29.6288, lon: -50.9999, blurb: "aberto até tarde" },
  { id: "acougue-vale-carnes-392", name: "Açougue Vale Carnes", category: "açougue", lat: -29.6891, lon: -51.1148, blurb: "carne fresca, corte na hora" },
  { id: "loja-veste-bem-393", name: "Loja Veste Bem", category: "loja de roupas", lat: -29.6655, lon: -51.1513, blurb: "roupa boa e barata" },
  { id: "pet-shop-vale-pet-394", name: "Pet Shop Vale Pet", category: "pet shop", lat: -29.6987, lon: -51.2296, blurb: "ração e banho e tosa" },
  { id: "hortifruti-verde-vale-395", name: "Hortifruti Verde Vale", category: "hortifruti", lat: -29.6622, lon: -51.1226, blurb: "fruta e verdura fresquinha" },
  { id: "padaria-colonial-396", name: "Padaria Colonial", category: "padaria", lat: -29.698, lon: -51.0691, blurb: "salgados fresquinhos" },
  { id: "cafeteria-ponto-do-cafe", name: "Cafeteria Ponto do Café", category: "café", lat: -29.6447, lon: -51.197, blurb: "cafezinho bom e barato" },
  { id: "clinica-odontologica-odonto-bem-398", name: "Clínica Odontológica Odonto Bem", category: "clínica odontológica", lat: -29.8063, lon: -51.1319, blurb: "avaliação rápida" },
  { id: "floricultura-buque-399", name: "Floricultura Buquê", category: "floricultura", lat: -29.6737, lon: -51.1683, blurb: "flores frescas todo dia" },
];
